version: '3'

services:
  browserquest-server1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_ID=1
    volumes:
      - ./server:/app/server
    networks:
      - browserquest-network

  browserquest-server2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_ID=2
    volumes:
      - ./server:/app/server
    networks:
      - browserquest-network

  browserquest-server3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_ID=3
    volumes:
      - ./server:/app/server
    networks:
      - browserquest-network

  nginx-loadbalancer:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - browserquest-server1
      - browserquest-server2
      - browserquest-server3
    networks:
      - browserquest-network

networks:
  browserquest-network:
    driver: bridge