version: "3.9"

services:
  browserquest:
    image: browserquest-app
    environment:
      - PORT=8000
    deploy:
      replicas: 3
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client:/usr/share/nginx/html:ro
    depends_on:
      - browserquest
